server:
  port: "50051"

services:
  rabbitMq: "amqp://test:test@host.docker.internal:5672/"

database:
  dbType: mongodb
  mongoConfig:
    address: "host.docker.internal:27017"
    dbName: "cap"
    dbUser: "cap-root"
    dbPass: "cap-root"

storage:
  storageType: ipfs
  storageConfig:
    clusterApiAddr: "/dns4/host.docker.internal/tcp/9094/http"
    ipfsApiAddr: "/dns4/host.docker.internal/tcp/5001/http"
    clusterUser: ""
    clusterPass: ""