server:
  port: "50051"

services:
  rabbitMq: "amqp://test:test@host.docker.internal:5672/"

database:
  ip: "localhost"
  port: "27017"
  dbName: "cap"
  dbUser: "cap-root"
  dbPass: "cap-root"

storage:
  clusterAPIAddr: "/dns4/host.docker.internal/tcp/9094/http"
  ipfsAPIAddr: "/dns4/host.docker.internal/tcp/5001/http"
  clusterUser: ""
  clusterPass: ""