server:
  port: "50051"

services:
  taskAllocator: "localhost:50052"

database:
  ip: "localhost"
  port: "27017"
  dbName: "cap"
  dbUser: "cap-root"
  dbPass: "cap-root"

storage:
  clusterAPIAddr: "/ip4/127.0.0.1/tcp/9094"
  ipfsAPIAddr: "/ip4/127.0.0.1/tcp/5001"
  clusterUser: ""
  clusterPass: ""