server:
  port: "50051"

database:
  ip: "localhost"
  port: "27017"
  dbName: "cap"
  dbUser: "cap-root"
  dbPass: "cap-root"

storage:
  clusterPeerAddr: "/ip4/127.0.0.1/tcp/9094"
  clusterUser: ""
  clusterPass: ""